### ISSUE TITLE
Databricks SQL endpoint

### ISSUE THREAD

**Issue by cbcoutinho** [databrickslabs/splunk-integration#35]
I see this integration addon allows users to query Databricks from Splunk. Does it support Databricks SQL endpoints as well as interactive clusters?

**Comment by zaferbil** [comment]
Yes @cbcoutinho, sql endpoints are supported

**Comment by cbcoutinho** [comment]
This is not mentioned anywhere in the documentation available in the README, nor can I find it when configuring the add-on in Splunk Cloud. Can you please expand a bit on how Databricks SQL Endpoints are supported by this add-on?

**Comment by cbcoutinho** [comment]
Ping @zaferbil
